# Generated by Django 5.2.9 on 2025-12-09 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('track_name', models.CharField(max_length=500)),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('valence', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('tempo', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('loudness', models.FloatField()),
                ('normalized_vector', models.JSONField()),
                ('finalized_vector', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackArtistLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextTrackMR.artist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextTrackMR.track')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='track',
            field=models.ManyToManyField(through='nextTrackMR.TrackArtistLink', to='nextTrackMR.track'),
        ),
    ]
