# Generated by Django 5.2.9 on 2025-12-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextTrackMR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='fixed_track_name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
